### ISSUE TITLE
superSmoother function

### ISSUE THREAD

**Issue by npatwa** [IlyaKipnis/DSTrading#6]
Hi Ilya,

First up, many thanks for making available the Dr. Ehler indicators in R. I am slowly exploring them and came across the superSmoother function.

I believe the line 

filt <- c1*(x+lag(x))/2

should actually be 

filt <- c1*(x+lag(x, k=-1))/2 to match Dr. Ehlers equation given in the book 'Cycle Analytics for Traders'.

Can you please check?

Thanks,

Najmuddin

**Comment by braverock** [comment]
lag(x, k=-1) would introduce look-ahead bias.

Is that what you want?

lag.xts lags a timeseries in the correct direction, and defaults to 1, so it will always lag 'back' from the current observation.  lag in base R lags the wrong direction (for time series).

**Comment by npatwa** [comment]
Hello,

Sorry my bad.

While the supersmoother works perfectly well for xts type objects, it doesn't have the leading NAs for zoo type objects. hence I felt there was somehting wrong with the code.

Thanks,

Najmuddin
