### ISSUE TITLE
R Version Compatibility

### ISSUE THREAD

**Issue by Sinansi** [IlyaKipnis/DSTrading#7]
Dears Sirs,

May you please upgrade this package to R version 3?
I received the following error during installation.

> install.packages('DSTrading', dependencies = TRUE)
Warning message:
package 'DSTrading' is not available (for R version 3.5.3)

Thank you so much for your time and effort!
Best regards.

**Comment by Esturban** [comment]
CRAN versions aren't up to date.  To install, use the github version via `devtools`

> devtools::install_github("IlyaKipnis/DSTrading")
Downloading GitHub repo IlyaKipnis/DSTrading@HEAD
√  checking for file 'C:\Users\USERNAME\AppData\Local\Temp\RtmpQJ4fzh\remotes298c5157567b\IlyaKipnis-DSTrading-09b29da/DESCRIPTION' (556ms)
> preparing 'DSTrading': (1s)
√  checking DESCRIPTION meta-information ... 
[... truncated...]
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
> DONE (DSTrading)

`devtools::install_github("IlyaKipnis/DSTrading")` this command should help you with the compatibility issue

**Comment by Sinansi** [comment]
Thank you!
